[package]
name = "rns-embedded-runtime"
version = "0.5.2"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Runtime support layer for embedded Reticulum transports and alloc-backed targets."

[dependencies]
rns-embedded-core = { path = "../rns-embedded-core", version = "0.5.2", default-features = false, features = ["alloc"] }

[features]
default = ["std"]
std = ["rns-embedded-core/std"]
alloc = ["rns-embedded-core/alloc"]

[lints]
workspace = true
