[package]
name = "lxmf-sdk"
version = "0.5.2"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "High-level Rust SDK for LXMF clients and RPC-backed LXMF workflows."
readme = "../../../README.md"
documentation = "https://docs.rs/lxmf-sdk"
keywords = ["lxmf", "sdk", "messaging", "reticulum"]
categories = ["network-programming", "api-bindings"]

[dependencies]
lxmf-reference.workspace = true
lxmf-core.workspace = true
rns-rpc = { workspace = true, optional = true }
rustls = { workspace = true, optional = true }
rustls-pemfile = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, optional = true }
tokio-rustls = { workspace = true, optional = true }
tokio-stream = { workspace = true, optional = true }
zeromq = { workspace = true, optional = true }
hmac.workspace = true
sha2.workspace = true
hex.workspace = true
zeroize.workspace = true

[features]
default = ["std", "sdk-async", "rpc-backend"]
std = []
sdk-async = ["dep:tokio", "dep:tokio-stream"]
rpc-backend = ["std", "dep:rns-rpc", "dep:rustls", "dep:rustls-pemfile", "dep:tokio-rustls"]
zmq-pipeline-backend = ["std", "sdk-async", "dep:rns-rpc", "dep:zeromq"]
embedded-alloc = []
loom-tests = []

[dev-dependencies]
criterion.workspace = true
loom.workspace = true

[package.metadata.cargo-udeps]
ignore = { development = ["loom"] }

[[bench]]
name = "sdk_client_paths"
harness = false

[[example]]
name = "zmq_pipeline_send"
required-features = ["zmq-pipeline-backend"]

[lints]
workspace = true
