const PROPAGATION_SDK_OPERATION_SPECS: &[SdkOperationSpec] = &[
    SdkOperationSpec {
        id: "app.propagation.peer_sync",
        group: "propagation",
        kind: "command",
        transport_variant: "legacy_rpc",
        description: "Run a propagation peer sync and return offer, transfer, retry, and queue state.",
        aliases: &["peer_sync"],
        required_capabilities: &[],
        rpc_method: "peer_sync",
    },
    SdkOperationSpec {
        id: "app.propagation.remote_status",
        group: "propagation",
        kind: "query",
        transport_variant: "legacy_rpc",
        description: "Query remote propagation router status.",
        aliases: &["propagation_remote_status"],
        required_capabilities: &[],
        rpc_method: "propagation_remote_status",
    },
    SdkOperationSpec {
        id: "app.propagation.remote_fetch",
        group: "propagation",
        kind: "command",
        transport_variant: "legacy_rpc",
        description: "Fetch propagation payloads from a remote router and preserve lifecycle state.",
        aliases: &["propagation_remote_fetch"],
        required_capabilities: &[],
        rpc_method: "propagation_remote_fetch",
    },
    SdkOperationSpec {
        id: "app.propagation.remote_download",
        group: "propagation",
        kind: "command",
        transport_variant: "legacy_rpc",
        description: "Download propagation payloads from a remote router and preserve lifecycle state.",
        aliases: &["propagation_remote_download"],
        required_capabilities: &[],
        rpc_method: "propagation_remote_download",
    },
    SdkOperationSpec {
        id: "app.propagation.remote_sync",
        group: "propagation",
        kind: "command",
        transport_variant: "legacy_rpc",
        description: "Run a remote propagation sync for one peer and preserve peer queue state.",
        aliases: &["propagation_remote_sync"],
        required_capabilities: &[],
        rpc_method: "propagation_remote_sync",
    },
    SdkOperationSpec {
        id: "app.propagation.remote_unpeer",
        group: "propagation",
        kind: "command",
        transport_variant: "legacy_rpc",
        description: "Unpeer through a remote propagation router and report local queue cleanup.",
        aliases: &["propagation_remote_unpeer"],
        required_capabilities: &[],
        rpc_method: "propagation_remote_unpeer",
    },
    SdkOperationSpec {
        id: "app.propagation.acknowledge_sync_completion",
        group: "propagation",
        kind: "command",
        transport_variant: "legacy_rpc",
        description: "Acknowledge a propagation sync completion or failure and expose the resulting recovery state.",
        aliases: &["propagation_acknowledge_sync_completion"],
        required_capabilities: &[],
        rpc_method: "propagation_acknowledge_sync_completion",
    },
    SdkOperationSpec {
        id: "app.propagation.node.get",
        group: "propagation",
        kind: "query",
        transport_variant: "legacy_rpc",
        description: "Return the selected outbound propagation router node.",
        aliases: &["get_outbound_propagation_node"],
        required_capabilities: &[],
        rpc_method: "get_outbound_propagation_node",
    },
    SdkOperationSpec {
        id: "app.propagation.node.cost",
        group: "propagation",
        kind: "query",
        transport_variant: "legacy_rpc",
        description: "Return the cached outbound propagation router stamp cost, or unavailable when no announce app-data has been learned.",
        aliases: &["get_outbound_propagation_cost"],
        required_capabilities: &[],
        rpc_method: "get_outbound_propagation_cost",
    },
    SdkOperationSpec {
        id: "app.propagation.node.set",
        group: "propagation",
        kind: "command",
        transport_variant: "legacy_rpc",
        description: "Select or clear the outbound propagation router node.",
        aliases: &["set_outbound_propagation_node"],
        required_capabilities: &[],
        rpc_method: "set_outbound_propagation_node",
    },
    SdkOperationSpec {
        id: "app.propagation.node.list",
        group: "propagation",
        kind: "query",
        transport_variant: "legacy_rpc",
        description: "List known outbound propagation router nodes and selection state.",
        aliases: &["list_propagation_nodes"],
        required_capabilities: &[],
        rpc_method: "list_propagation_nodes",
    },
    SdkOperationSpec {
        id: "app.propagation.status",
        group: "propagation",
        kind: "query",
        transport_variant: "legacy_rpc",
        description: "Return local propagation configuration, counters, sync state, and selected router state.",
        aliases: &["propagation_status"],
        required_capabilities: &[],
        rpc_method: "propagation_status",
    },
    SdkOperationSpec {
        id: "app.propagation.enable",
        group: "propagation",
        kind: "command",
        transport_variant: "legacy_rpc",
        description: "Enable or update local propagation configuration and return the resulting state.",
        aliases: &["propagation_enable"],
        required_capabilities: &[],
        rpc_method: "propagation_enable",
    },
    SdkOperationSpec {
        id: "app.propagation.delivery_policy.get",
        group: "propagation",
        kind: "query",
        transport_variant: "legacy_rpc",
        description: "Return the local propagation delivery policy.",
        aliases: &["get_delivery_policy"],
        required_capabilities: &[],
        rpc_method: "get_delivery_policy",
    },
    SdkOperationSpec {
        id: "app.propagation.delivery_policy.set",
        group: "propagation",
        kind: "command",
        transport_variant: "legacy_rpc",
        description: "Update the local propagation delivery policy and return the resulting policy.",
        aliases: &["set_delivery_policy"],
        required_capabilities: &[],
        rpc_method: "set_delivery_policy",
    },
    SdkOperationSpec {
        id: "app.propagation.peer_maintenance",
        group: "propagation",
        kind: "command",
        transport_variant: "legacy_rpc",
        description: "Cull, rotate, and sync propagation peers while reporting cleanup and retry state.",
        aliases: &["propagation_peer_maintenance"],
        required_capabilities: &[],
        rpc_method: "propagation_peer_maintenance",
    },
    SdkOperationSpec {
        id: "app.propagation.ingest",
        group: "propagation",
        kind: "command",
        transport_variant: "legacy_rpc",
        description: "Ingest a local propagation payload into durable propagation storage and return queue accounting.",
        aliases: &["propagation_ingest"],
        required_capabilities: &[],
        rpc_method: "propagation_ingest",
    },
    SdkOperationSpec {
        id: "app.propagation.fetch",
        group: "propagation",
        kind: "command",
        transport_variant: "legacy_rpc",
        description: "Fetch a local propagation payload from memory or durable propagation storage.",
        aliases: &["propagation_fetch"],
        required_capabilities: &[],
        rpc_method: "propagation_fetch",
    },
];
