const SDK_OPERATION_SPECS: &[SdkOperationSpec] = &[
    SdkOperationSpec {
        id: "app.runtime.status",
        group: "runtime",
        kind: "query",
        transport_variant: "rpc",
        description: "Return runtime status and queue counters.",
        aliases: &["sdk_snapshot_v2"],
        required_capabilities: &[],
        rpc_method: "sdk_snapshot_v2",
    },
    SdkOperationSpec {
        id: "app.runtime.cursor_hint",
        group: "runtime",
        kind: "query",
        transport_variant: "rpc",
        description:
            "Return the latest remembered pagination cursor for one method or all methods.",
        aliases: &["sdk_cursor_hint_v2"],
        required_capabilities: &[],
        rpc_method: "sdk_cursor_hint_v2",
    },
    SdkOperationSpec {
        id: "app.delivery.send",
        group: "delivery",
        kind: "command",
        transport_variant: "rpc",
        description: "Queue one outbound message for delivery.",
        aliases: &["sdk_send_v2"],
        required_capabilities: &[],
        rpc_method: "sdk_send_v2",
    },
    SdkOperationSpec {
        id: "app.delivery.send_batch",
        group: "delivery",
        kind: "command",
        transport_variant: "rpc",
        description: "Queue an ordered batch of outbound messages for delivery.",
        aliases: &["sdk_send_batch_v2"],
        required_capabilities: &[],
        rpc_method: "sdk_send_batch_v2",
    },
    SdkOperationSpec {
        id: "app.delivery.status",
        group: "delivery",
        kind: "query",
        transport_variant: "rpc",
        description: "Return delivery state for a specific message id.",
        aliases: &["sdk_status_v2"],
        required_capabilities: &[],
        rpc_method: "sdk_status_v2",
    },
    SdkOperationSpec {
        id: "app.delivery.cancel",
        group: "delivery",
        kind: "command",
        transport_variant: "rpc",
        description: "Cancel a queued outbound message when it has not reached a terminal state.",
        aliases: &["sdk_cancel_message_v2"],
        required_capabilities: &[],
        rpc_method: "sdk_cancel_message_v2",
    },
    SdkOperationSpec {
        id: "app.event.poll",
        group: "events",
        kind: "query",
        transport_variant: "rpc",
        description: "Poll batches of runtime events.",
        aliases: &["sdk_poll_events_v2"],
        required_capabilities: &[],
        rpc_method: "sdk_poll_events_v2",
    },
    SdkOperationSpec {
        id: "app.identity.list",
        group: "identity",
        kind: "query",
        transport_variant: "rpc",
        description: "List identities visible to the runtime.",
        aliases: &["sdk_identity_list_v2"],
        required_capabilities: &["sdk.capability.identity_multi"],
        rpc_method: "sdk_identity_list_v2",
    },
    SdkOperationSpec {
        id: "app.identity.announce",
        group: "identity",
        kind: "command",
        transport_variant: "rpc",
        description: "Trigger an announce for the active identity.",
        aliases: &["sdk_identity_announce_now_v2"],
        required_capabilities: &["sdk.capability.identity_discovery"],
        rpc_method: "sdk_identity_announce_now_v2",
    },
    SdkOperationSpec {
        id: "app.identity.presence.list",
        group: "identity",
        kind: "query",
        transport_variant: "rpc",
        description: "List recently seen peers and announce-derived presence state.",
        aliases: &["sdk_identity_presence_list_v2"],
        required_capabilities: &["sdk.capability.identity_discovery"],
        rpc_method: "sdk_identity_presence_list_v2",
    },
    SdkOperationSpec {
        id: "app.contact.list",
        group: "identity",
        kind: "query",
        transport_variant: "rpc",
        description: "List contacts for a selected identity.",
        aliases: &["sdk_identity_contact_list_v2"],
        required_capabilities: &["sdk.capability.contact_management"],
        rpc_method: "sdk_identity_contact_list_v2",
    },
    SdkOperationSpec {
        id: "app.contact.update",
        group: "identity",
        kind: "command",
        transport_variant: "rpc",
        description: "Create or update a contact record for an identity.",
        aliases: &["sdk_identity_contact_update_v2"],
        required_capabilities: &["sdk.capability.contact_management"],
        rpc_method: "sdk_identity_contact_update_v2",
    },
    SdkOperationSpec {
        id: "app.identity.bootstrap",
        group: "identity",
        kind: "command",
        transport_variant: "rpc",
        description: "Bootstrap trust and optional sync state for an identity.",
        aliases: &["sdk_identity_bootstrap_v2"],
        required_capabilities: &["sdk.capability.contact_management"],
        rpc_method: "sdk_identity_bootstrap_v2",
    },
    SdkOperationSpec {
        id: "app.peer.connect",
        group: "peer",
        kind: "command",
        transport_variant: "rpc",
        description: "Connect to a saved peer and return lifecycle metadata.",
        aliases: &["sdk_peer_connect_v2"],
        required_capabilities: &["sdk.capability.peer_lifecycle"],
        rpc_method: "sdk_peer_connect_v2",
    },
    SdkOperationSpec {
        id: "app.peer.disconnect",
        group: "peer",
        kind: "command",
        transport_variant: "rpc",
        description: "Disconnect a saved peer and return lifecycle metadata.",
        aliases: &["sdk_peer_disconnect_v2"],
        required_capabilities: &["sdk.capability.peer_lifecycle"],
        rpc_method: "sdk_peer_disconnect_v2",
    },
    SdkOperationSpec {
        id: "app.peer.reconnect",
        group: "peer",
        kind: "command",
        transport_variant: "rpc",
        description: "Reconnect a saved peer and return lifecycle metadata.",
        aliases: &["sdk_peer_reconnect_v2"],
        required_capabilities: &["sdk.capability.peer_lifecycle"],
        rpc_method: "sdk_peer_reconnect_v2",
    },
    SdkOperationSpec {
        id: "app.workflow.peer_ready",
        group: "workflow",
        kind: "command",
        transport_variant: "rpc",
        description: "Ensure a peer contact exists and optionally announce before use.",
        aliases: &["sdk_workflow_peer_ready_v2"],
        required_capabilities: &[
            "sdk.capability.contact_management",
            "sdk.capability.identity_discovery",
        ],
        rpc_method: "sdk_workflow_peer_ready_v2",
    },
    SdkOperationSpec {
        id: "app.workflow.topic_sync",
        group: "workflow",
        kind: "command",
        transport_variant: "rpc",
        description: "Ensure a topic exists, subscribe to it, and fetch a telemetry snapshot.",
        aliases: &["sdk_workflow_topic_sync_v2"],
        required_capabilities: &[
            "sdk.capability.topics",
            "sdk.capability.topic_subscriptions",
            "sdk.capability.telemetry_query",
        ],
        rpc_method: "sdk_workflow_topic_sync_v2",
    },
    SdkOperationSpec {
        id: "app.workflow.attachment_report_publish",
        group: "workflow",
        kind: "command",
        transport_variant: "rpc",
        description: "Ensure a topic, store an attachment, and publish a summary report.",
        aliases: &["sdk_workflow_attachment_report_publish_v2"],
        required_capabilities: &[
            "sdk.capability.topics",
            "sdk.capability.attachments",
            "sdk.capability.topic_fanout",
        ],
        rpc_method: "sdk_workflow_attachment_report_publish_v2",
    },
    SdkOperationSpec {
        id: "app.workflow.mission_update_send",
        group: "workflow",
        kind: "command",
        transport_variant: "rpc",
        description:
            "Ensure peer and optional topic state, store attachments, and send a mission update.",
        aliases: &["sdk_workflow_mission_update_send_v2"],
        required_capabilities: &[
            "sdk.capability.contact_management",
            "sdk.capability.identity_discovery",
            "sdk.capability.topics",
            "sdk.capability.attachments",
        ],
        rpc_method: "sdk_workflow_mission_update_send_v2",
    },
    SdkOperationSpec {
        id: "app.topic.create",
        group: "topics",
        kind: "command",
        transport_variant: "rpc",
        description: "Create a topic record for collaborative app flows.",
        aliases: &["sdk_topic_create_v2"],
        required_capabilities: &["sdk.capability.topics"],
        rpc_method: "sdk_topic_create_v2",
    },
    SdkOperationSpec {
        id: "app.topic.get",
        group: "topics",
        kind: "query",
        transport_variant: "rpc",
        description: "Fetch one topic record by id.",
        aliases: &["sdk_topic_get_v2"],
        required_capabilities: &["sdk.capability.topics"],
        rpc_method: "sdk_topic_get_v2",
    },
    SdkOperationSpec {
        id: "app.topic.list",
        group: "topics",
        kind: "query",
        transport_variant: "rpc",
        description: "List known topics with cursor pagination.",
        aliases: &["sdk_topic_list_v2"],
        required_capabilities: &["sdk.capability.topics"],
        rpc_method: "sdk_topic_list_v2",
    },
    SdkOperationSpec {
        id: "app.topic.subscribe",
        group: "topics",
        kind: "command",
        transport_variant: "rpc",
        description: "Subscribe the runtime to topic updates.",
        aliases: &["sdk_topic_subscribe_v2"],
        required_capabilities: &["sdk.capability.topic_subscriptions"],
        rpc_method: "sdk_topic_subscribe_v2",
    },
    SdkOperationSpec {
        id: "app.topic.unsubscribe",
        group: "topics",
        kind: "command",
        transport_variant: "rpc",
        description: "Remove a topic subscription from the runtime.",
        aliases: &["sdk_topic_unsubscribe_v2"],
        required_capabilities: &["sdk.capability.topic_subscriptions"],
        rpc_method: "sdk_topic_unsubscribe_v2",
    },
    SdkOperationSpec {
        id: "app.topic.publish",
        group: "topics",
        kind: "command",
        transport_variant: "rpc",
        description: "Publish one payload fanout to a topic.",
        aliases: &["sdk_topic_publish_v2"],
        required_capabilities: &["sdk.capability.topic_fanout"],
        rpc_method: "sdk_topic_publish_v2",
    },
    SdkOperationSpec {
        id: "app.telemetry.query",
        group: "telemetry",
        kind: "query",
        transport_variant: "rpc",
        description: "Query telemetry points filtered by peer, topic, and time bounds.",
        aliases: &["sdk_telemetry_query_v2"],
        required_capabilities: &["sdk.capability.telemetry_query"],
        rpc_method: "sdk_telemetry_query_v2",
    },
    SdkOperationSpec {
        id: "app.telemetry.subscribe",
        group: "telemetry",
        kind: "command",
        transport_variant: "rpc",
        description: "Subscribe the runtime to telemetry stream updates.",
        aliases: &["sdk_telemetry_subscribe_v2"],
        required_capabilities: &["sdk.capability.telemetry_stream"],
        rpc_method: "sdk_telemetry_subscribe_v2",
    },
    SdkOperationSpec {
        id: "app.attachment.store",
        group: "attachments",
        kind: "command",
        transport_variant: "rpc",
        description: "Store one attachment payload with optional topic associations.",
        aliases: &["sdk_attachment_store_v2"],
        required_capabilities: &["sdk.capability.attachments"],
        rpc_method: "sdk_attachment_store_v2",
    },
    SdkOperationSpec {
        id: "app.attachment.get",
        group: "attachments",
        kind: "query",
        transport_variant: "rpc",
        description: "Fetch one attachment metadata record by id.",
        aliases: &["sdk_attachment_get_v2"],
        required_capabilities: &["sdk.capability.attachments"],
        rpc_method: "sdk_attachment_get_v2",
    },
    SdkOperationSpec {
        id: "app.attachment.list",
        group: "attachments",
        kind: "query",
        transport_variant: "rpc",
        description: "List stored attachments with topic filtering and cursor pagination.",
        aliases: &["sdk_attachment_list_v2"],
        required_capabilities: &["sdk.capability.attachments"],
        rpc_method: "sdk_attachment_list_v2",
    },
    SdkOperationSpec {
        id: "app.attachment.delete",
        group: "attachments",
        kind: "command",
        transport_variant: "rpc",
        description: "Delete one stored attachment by id.",
        aliases: &["sdk_attachment_delete_v2"],
        required_capabilities: &["sdk.capability.attachment_delete"],
        rpc_method: "sdk_attachment_delete_v2",
    },
    SdkOperationSpec {
        id: "app.attachment.associate_topic",
        group: "attachments",
        kind: "command",
        transport_variant: "rpc",
        description: "Associate an existing attachment with an additional topic.",
        aliases: &["sdk_attachment_associate_topic_v2"],
        required_capabilities: &["sdk.capability.attachments"],
        rpc_method: "sdk_attachment_associate_topic_v2",
    },
    SdkOperationSpec {
        id: "app.attachment.upload_start",
        group: "attachments",
        kind: "command",
        transport_variant: "rpc",
        description: "Open a chunked attachment upload session.",
        aliases: &["sdk_attachment_upload_start_v2"],
        required_capabilities: &["sdk.capability.attachment_streaming"],
        rpc_method: "sdk_attachment_upload_start_v2",
    },
    SdkOperationSpec {
        id: "app.attachment.upload_chunk",
        group: "attachments",
        kind: "command",
        transport_variant: "rpc",
        description: "Append one chunk to an attachment upload session.",
        aliases: &["sdk_attachment_upload_chunk_v2"],
        required_capabilities: &["sdk.capability.attachment_streaming"],
        rpc_method: "sdk_attachment_upload_chunk_v2",
    },
    SdkOperationSpec {
        id: "app.attachment.upload_commit",
        group: "attachments",
        kind: "command",
        transport_variant: "rpc",
        description: "Commit a completed attachment upload session.",
        aliases: &["sdk_attachment_upload_commit_v2"],
        required_capabilities: &["sdk.capability.attachment_streaming"],
        rpc_method: "sdk_attachment_upload_commit_v2",
    },
    SdkOperationSpec {
        id: "app.attachment.download_chunk",
        group: "attachments",
        kind: "query",
        transport_variant: "rpc",
        description: "Read one chunk from a stored attachment payload.",
        aliases: &["sdk_attachment_download_chunk_v2"],
        required_capabilities: &["sdk.capability.attachment_streaming"],
        rpc_method: "sdk_attachment_download_chunk_v2",
    },
    SdkOperationSpec {
        id: "app.marker.create",
        group: "markers",
        kind: "command",
        transport_variant: "rpc",
        description: "Create a shared marker anchored to an optional topic.",
        aliases: &["sdk_marker_create_v2"],
        required_capabilities: &["sdk.capability.markers"],
        rpc_method: "sdk_marker_create_v2",
    },
    SdkOperationSpec {
        id: "app.marker.list",
        group: "markers",
        kind: "query",
        transport_variant: "rpc",
        description: "List markers with topic filtering and cursor pagination.",
        aliases: &["sdk_marker_list_v2"],
        required_capabilities: &["sdk.capability.markers"],
        rpc_method: "sdk_marker_list_v2",
    },
    SdkOperationSpec {
        id: "app.marker.update_position",
        group: "markers",
        kind: "command",
        transport_variant: "rpc",
        description: "Move an existing marker while enforcing revision checks.",
        aliases: &["sdk_marker_update_position_v2"],
        required_capabilities: &["sdk.capability.markers"],
        rpc_method: "sdk_marker_update_position_v2",
    },
    SdkOperationSpec {
        id: "app.marker.delete",
        group: "markers",
        kind: "command",
        transport_variant: "rpc",
        description: "Delete an existing marker while enforcing revision checks.",
        aliases: &["sdk_marker_delete_v2"],
        required_capabilities: &["sdk.capability.markers"],
        rpc_method: "sdk_marker_delete_v2",
    },
    SdkOperationSpec {
        id: "app.voice.session.open",
        group: "voice",
        kind: "command",
        transport_variant: "rpc",
        description: "Open a voice signaling session for a peer.",
        aliases: &["sdk_voice_session_open_v2"],
        required_capabilities: &["sdk.capability.voice_signaling"],
        rpc_method: "sdk_voice_session_open_v2",
    },
    SdkOperationSpec {
        id: "app.voice.session.update",
        group: "voice",
        kind: "command",
        transport_variant: "rpc",
        description: "Advance the state of a voice signaling session.",
        aliases: &["sdk_voice_session_update_v2"],
        required_capabilities: &["sdk.capability.voice_signaling"],
        rpc_method: "sdk_voice_session_update_v2",
    },
    SdkOperationSpec {
        id: "app.voice.session.close",
        group: "voice",
        kind: "command",
        transport_variant: "rpc",
        description: "Close a voice signaling session.",
        aliases: &["sdk_voice_session_close_v2"],
        required_capabilities: &["sdk.capability.voice_signaling"],
        rpc_method: "sdk_voice_session_close_v2",
    },
    SdkOperationSpec {
        id: "app.message.history.list",
        group: "messaging",
        kind: "query",
        transport_variant: "legacy_rpc",
        description: "List message history records for app chat flows.",
        aliases: &["list_messages"],
        required_capabilities: &[],
        rpc_method: "list_messages",
    },
    SdkOperationSpec {
        id: "app.delivery.destination_hash",
        group: "identity",
        kind: "query",
        transport_variant: "legacy_rpc",
        description: "Resolve the runtime delivery destination hash.",
        aliases: &["status"],
        required_capabilities: &[],
        rpc_method: "status",
    },
];
