[package]
name = "rns-embedded-mininode"
version = "0.5.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Minimal embedded Reticulum node helpers for constrained LXMF deployments."

[dependencies]
hex.workspace = true
lxmf-core = { package = "lxmf-wire", path = "../lxmf-core", version = "0.5.1", default-features = false, features = ["alloc"] }
rand_core.workspace = true
rmp-serde.workspace = true
rmpv.workspace = true
rns-core = { package = "reticulum-rs-core", path = "../rns-core", version = "0.5.1", default-features = false, features = ["alloc"] }

[features]
default = ["std"]
std = ["lxmf-core/std", "rns-core/std"]

[lints]
workspace = true
