[package]
name = "lxmf-embedded-mini"
version = "0.5.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "No-alloc mini LXMF runtime for embedded targets."

[dependencies]
heapless = "0.8"

[dev-dependencies]
lxmf-core.workspace = true

[features]
default = []

[lints]
workspace = true
